USE_CAMERA_STUB := false
-include vendor/asus/tf101/BoardConfigVendor.mk
USE_PROPRIETARY_AUDIO_EXTENSIONS := false
SMALLER_FONT_FOOTPRINT := true

# CPU
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_SMP := true
TARGET_ARCH_VARIANT := armv7-a
TARGET_BOARD_PLATFORM := tegra
ARCH_ARM_HAVE_TLS_REGISTER := true
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_BOOTLOADER_BOARD_NAME := tegra
TARGET_ARCH_VARIANT_FPU := vfpv3-d16

# Misc

TARGET_PREBUILT_KERNEL := device/asus/tf101/kernel
BOARD_HAS_NO_SELECT_BUTTON := true
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true
TARGET_NO_RECOVERYIMAGE := true
TARGET_PROVIDES_INIT_RC := true

# Storage 
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 251658240
BOARD_USERDATAIMAGE_PARTITION_SIZE := 31399067648
BOARD_FLASH_BLOCK_SIZE := 4096
BOARD_HAS_LARGE_FILESYSTEM := true

# Audio
BOARD_USES_GENERIC_AUDIO := false
USE_PROPRIETARY_AUDIO_EXTENSIONS := false

# EGL
USE_OPENGL_RENDERER := true
BOARD_EGL_CFG := device/asus/tf101/egl.cfg

